# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AgricultureMapping
                                 A QGIS plugin
 Plugin professionnel de cartographie des cultures avec ML et GEE
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-25
        copyright            : (C) 2025 by Hiba Aamnous - Pôle Digital Agriculture
        email                : hibaamnous@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AgricultureMapping class from file AgricultureMapping.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .agriculture_mapping_plugin import AgricultureMapping
    return AgricultureMapping(iface)
